import { useRouter } from "expo-router";
import { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { AuthScaffold } from "@/components/auth/AuthScaffold";
import { AuthProviderButton } from "@/components/foundation/AuthProviderButton";
import { PrimaryButton, TextButton } from "@/components/foundation/Buttons";
import { InlineError } from "@/components/foundation/Feedback";
import { FormField, PasswordField } from "@/components/foundation/FormField";
import { colors, spacing, typography } from "@/theme/tokens";

export default function SignUpScreen() { const router = useRouter(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const submit = () => { if (!name.trim() || !email.includes("@") || password.length < 8 || password !== confirm) { setError("Check your name, email, and matching 8-character passwords."); return; } setError(""); setLoading(true); setTimeout(() => { setLoading(false); router.push({ pathname: "/(auth)/verify-email", params: { email } }); }, 650); }; return <AuthScaffold description="Build a local demo profile—no account is sent anywhere." title="Create your account"><FormField label="Full name" onChangeText={setName} placeholder="Your name" value={name} /><FormField autoCapitalize="none" keyboardType="email-address" label="Email" onChangeText={setEmail} placeholder="you@example.com" value={email} /><PasswordField label="Password" onChangeText={setPassword} placeholder="8+ characters" value={password} /><Text style={styles.hint}>Use 8+ characters with a number for a stronger password.</Text><PasswordField label="Confirm password" onChangeText={setConfirm} placeholder="Repeat password" value={confirm} />{error ? <InlineError message={error} /> : null}<PrimaryButton label="Create account" loading={loading} onPress={submit} /><View style={styles.providers}><AuthProviderButton provider="Apple" onPress={() => setError("Apple sign-up is not connected in this local demo.")} /><AuthProviderButton provider="Google" onPress={() => setError("Google sign-up is not connected in this local demo.")} /></View><Text style={styles.terms}>By continuing, you acknowledge the demo Terms and Privacy notice. No real account is created.</Text><View style={styles.login}><Text style={styles.hint}>Already joined?</Text><TextButton label="Log in" onPress={() => router.replace("/(auth)/login")} /></View></AuthScaffold>; }
const styles = StyleSheet.create({ hint: { ...typography.caption, color: colors.textTertiary }, providers: { flexDirection: "row", gap: spacing.sm }, terms: { ...typography.caption, color: colors.textTertiary, textAlign: "center" }, login: { flexDirection: "row", alignItems: "center", justifyContent: "center" } });
