import { Ionicons } from "@expo/vector-icons";
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, View } from "react-native";
import { colors, radii, spacing, typography } from "@/theme/tokens";
import { PrimaryButton, SecondaryButton } from "./Buttons";

export function InlineError({ message }: { message: string }) { return <View accessibilityLiveRegion="assertive" style={styles.inline}><Ionicons color={colors.negative} name="alert-circle" size={18} /><Text style={styles.inlineText}>{message}</Text></View>; }
export function OfflineBanner() { return <View style={styles.offline}><Ionicons color={colors.warning} name="cloud-offline-outline" size={17} /><Text style={styles.offlineText}>Offline demo state — your local choices are safe.</Text></View>; }
export function DemoDataBadge() { return <View style={styles.badge}><Text style={styles.badgeText}>LOCAL DEMO</Text></View>; }
export function LoadingOverlay({ visible, label = "Loading" }: { visible: boolean; label?: string }) { return <Modal transparent visible={visible}><View accessibilityLabel={label} accessibilityRole="progressbar" style={styles.overlay}><View style={styles.loading}><ActivityIndicator color={colors.teal} /><Text style={styles.loadingText}>{label}</Text></View></View></Modal>; }
export function ErrorState({ title, description, onRetry }: { title: string; description: string; onRetry: () => void }) { return <View style={styles.state}><Ionicons color={colors.negative} name="alert-circle-outline" size={30} /><Text style={styles.stateTitle}>{title}</Text><Text style={styles.stateBody}>{description}</Text><SecondaryButton label="Try again" onPress={onRetry} /></View>; }
export function ConfirmationModal({ visible, title, description, onConfirm, onCancel }: { visible: boolean; title: string; description: string; onConfirm: () => void; onCancel: () => void }) { return <Modal animationType="fade" transparent visible={visible}><View style={styles.overlay}><View accessibilityViewIsModal style={styles.modal}><Text style={styles.stateTitle}>{title}</Text><Text style={styles.stateBody}>{description}</Text><PrimaryButton label="Confirm" onPress={onConfirm} /><Pressable onPress={onCancel}><Text style={styles.cancel}>Cancel</Text></Pressable></View></View></Modal>; }
const styles = StyleSheet.create({
  inline: { flexDirection: "row", alignItems: "flex-start", gap: spacing.xs, padding: spacing.sm, borderRadius: radii.sm, backgroundColor: "#32171B" }, inlineText: { ...typography.caption, flex: 1, color: colors.negative }, offline: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: spacing.xs, backgroundColor: "#322817", paddingHorizontal: spacing.md }, offlineText: { ...typography.caption, color: colors.warning }, badge: { alignSelf: "flex-start", borderRadius: radii.pill, backgroundColor: colors.tealMuted, paddingVertical: 5, paddingHorizontal: 9 }, badgeText: { ...typography.caption, color: colors.teal, letterSpacing: .8 }, overlay: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: colors.overlay, padding: spacing.lg }, loading: { flexDirection: "row", gap: spacing.sm, padding: spacing.lg, borderRadius: radii.lg, backgroundColor: colors.surfaceElevated }, loadingText: { ...typography.body, color: colors.textPrimary }, state: { alignItems: "center", gap: spacing.sm, padding: spacing.xl }, stateTitle: { ...typography.heading, color: colors.textPrimary, textAlign: "center" }, stateBody: { ...typography.body, color: colors.textSecondary, textAlign: "center", marginBottom: spacing.sm }, modal: { width: "100%", maxWidth: 420, gap: spacing.md, padding: spacing.xl, borderRadius: radii.hero, backgroundColor: colors.surfaceElevated, borderWidth: 1, borderColor: colors.border }, cancel: { ...typography.label, color: colors.textSecondary, textAlign: "center", padding: spacing.sm },
});
