import assert from "node:assert/strict";
import test from "node:test";
import { addStock,initialWatchlistState,migrateOnboardingStocks,moveStock,removeStock,resolveHydratedWatchlist,watchlistReducer,WATCHLIST_LIMIT } from "../src/features/watchlist/model.ts";
import { loadWatchlistFrom,saveWatchlistTo,WATCHLIST_STORAGE_KEY } from "../src/storage/watchlistCore.ts";
import type { StorageAdapter } from "../src/storage/preferencesCore.ts";
import { getChartSeries } from "../src/data/stocks/charts.ts";
import { selectTodayWatchlist } from "../src/features/watchlist/todayStocks.ts";

test("watchlist add prevents duplicates and enforces the free limit",()=>{let symbols=addStock([],"AAPL");symbols=addStock(symbols,"AAPL");assert.deepEqual(symbols,["AAPL"]);const additions=["MSFT","NVDA","TSLA","AMZN","GOOGL","META","AMD","PLTR","NFLX","JPM","V","COST","WMT","DIS","KO"];for(const symbol of additions)symbols=addStock(symbols,symbol);assert.equal(symbols.length,WATCHLIST_LIMIT);assert.equal(symbols.includes("KO"),false);});
test("watchlist remove and reorder are deterministic",()=>{const symbols=["AAPL","MSFT","NVDA"] as const;assert.deepEqual(removeStock([...symbols],"MSFT"),["AAPL","NVDA"]);assert.deepEqual(moveStock([...symbols],"NVDA",-1),["AAPL","NVDA","MSFT"]);assert.deepEqual(moveStock([...symbols],"AAPL",-1),[...symbols]);});
test("onboarding stocks migrate once into the shared state model",()=>{assert.deepEqual(migrateOnboardingStocks(["AAPL","NVDA","TSLA"]).symbols,["AAPL","NVDA","TSLA"]);});
test("onboarding selection populates an already-created empty watchlist before completion",()=>{const migrated=resolveHydratedWatchlist(initialWatchlistState,["AAPL","NVDA","AMD"],false);assert.deepEqual(migrated.symbols,["AAPL","NVDA","AMD"]);const intentionallyEmpty=resolveHydratedWatchlist(initialWatchlistState,["AAPL","NVDA","AMD"],true);assert.deepEqual(intentionallyEmpty.symbols,[]);});
test("chart range, recent searches and order persist",async()=>{let state=watchlistReducer(initialWatchlistState,{type:"hydrate",value:migrateOnboardingStocks(["AAPL","NVDA","TSLA"])});state=watchlistReducer(state,{type:"move",symbol:"TSLA",direction:-1});state=watchlistReducer(state,{type:"recent",symbol:"NVDA"});state=watchlistReducer(state,{type:"range",symbol:"NVDA",range:"3M"});const values=new Map<string,string>();const adapter:StorageAdapter={getItem:async key=>values.get(key)??null,setItem:async(key,value)=>{values.set(key,value)},removeItem:async key=>{values.delete(key)}};await saveWatchlistTo(state,adapter);assert.ok(values.has(WATCHLIST_STORAGE_KEY));assert.deepEqual(await loadWatchlistFrom(adapter),state);});
test("every local chart range ends at the displayed quote",()=>{for(const range of ["1D","1W","1M","3M","1Y"] as const){const points=getChartSeries("NVDA",range,182.41);assert.equal(points.at(-1)?.value,182.41);}});
test("Today follows shared watchlist add, order, remove and empty state",()=>{let state=watchlistReducer(initialWatchlistState,{type:"add",symbol:"NVDA"});state=watchlistReducer(state,{type:"add",symbol:"AAPL"});assert.deepEqual(selectTodayWatchlist(state.symbols).map(stock=>stock.symbol),["NVDA","AAPL"]);state=watchlistReducer(state,{type:"move",symbol:"AAPL",direction:-1});assert.deepEqual(selectTodayWatchlist(state.symbols).map(stock=>stock.symbol),["AAPL","NVDA"]);state=watchlistReducer(state,{type:"remove",symbol:"AAPL"});assert.deepEqual(selectTodayWatchlist(state.symbols).map(stock=>stock.symbol),["NVDA"]);state=watchlistReducer(state,{type:"remove",symbol:"NVDA"});assert.deepEqual(selectTodayWatchlist(state.symbols),[]);});
