import assert from "node:assert/strict";
import test from "node:test";
import { addStock,initialWatchlistState,migrateOnboardingStocks,moveStock,removeStock,watchlistReducer,WATCHLIST_LIMIT } from "../src/features/watchlist/model.ts";
import { loadWatchlistFrom,saveWatchlistTo,WATCHLIST_STORAGE_KEY } from "../src/storage/watchlistCore.ts";
import type { StorageAdapter } from "../src/storage/preferencesCore.ts";

test("watchlist add prevents duplicates and enforces the free limit",()=>{let symbols=addStock([],"AAPL");symbols=addStock(symbols,"AAPL");assert.deepEqual(symbols,["AAPL"]);for(const symbol of ["MSFT","NVDA","TSLA","AMZN","GOOGL"] as const)symbols=addStock(symbols,symbol);assert.equal(symbols.length,WATCHLIST_LIMIT);assert.equal(symbols.includes("GOOGL"),false);});
test("watchlist remove and reorder are deterministic",()=>{const symbols=["AAPL","MSFT","NVDA"] as const;assert.deepEqual(removeStock([...symbols],"MSFT"),["AAPL","NVDA"]);assert.deepEqual(moveStock([...symbols],"NVDA",-1),["AAPL","NVDA","MSFT"]);assert.deepEqual(moveStock([...symbols],"AAPL",-1),[...symbols]);});
test("onboarding stocks migrate once into the shared state model",()=>{assert.deepEqual(migrateOnboardingStocks(["AAPL","NVDA","TSLA"]).symbols,["AAPL","NVDA","TSLA"]);});
test("chart range, recent searches and order persist",async()=>{let state=watchlistReducer(initialWatchlistState,{type:"hydrate",value:migrateOnboardingStocks(["AAPL","NVDA","TSLA"])});state=watchlistReducer(state,{type:"move",symbol:"TSLA",direction:-1});state=watchlistReducer(state,{type:"recent",symbol:"NVDA"});state=watchlistReducer(state,{type:"range",symbol:"NVDA",range:"3M"});const values=new Map<string,string>();const adapter:StorageAdapter={getItem:async key=>values.get(key)??null,setItem:async(key,value)=>{values.set(key,value)},removeItem:async key=>{values.delete(key)}};await saveWatchlistTo(state,adapter);assert.ok(values.has(WATCHLIST_STORAGE_KEY));assert.deepEqual(await loadWatchlistFrom(adapter),state);});
