import { Ionicons } from "@expo/vector-icons";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { DemoDataBadge } from "@/components/foundation/Feedback";
import { Screen } from "@/components/foundation/Screen";
import { colors, radii, spacing, typography } from "@/theme/tokens";

const briefs = [{ icon: "sunny-outline" as const, label: "MORNING", title: "Before the opening bell", time: "6:30 AM local", body: "Overnight moves, the day’s key events and companies worth watching." }, { icon: "moon-outline" as const, label: "EVENING", title: "After the closing bell", time: "5:30 PM local", body: "The session explained clearly, with tomorrow’s calendar in view." }];
export default function BriefsScreen() { return <Screen><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><View style={styles.header}><DemoDataBadge /><Text style={styles.title}>Briefs</Text><Text style={styles.subtitle}>Your market day, distilled into two calm moments.</Text></View><View style={styles.stack}>{briefs.map(brief => <View accessibilityLabel={`${brief.label} brief preview`} key={brief.label} style={styles.card}><View style={styles.icon}><Ionicons color={colors.teal} name={brief.icon} size={24} /></View><Text style={styles.label}>{brief.label} BRIEF</Text><Text style={styles.cardTitle}>{brief.title}</Text><Text style={styles.time}>{brief.time}</Text><Text style={styles.body}>{brief.body}</Text><View style={styles.preview}><Ionicons color={colors.warning} name="sparkles-outline" size={18} /><Text style={styles.previewText}>Preview only · brief generation arrives in Milestone 4</Text></View></View>)}</View><Text style={styles.note}>No AI model, news feed or external data source is connected in this milestone.</Text></ScrollView></Screen>; }
const styles = StyleSheet.create({ scroll: { width: "100%", maxWidth: 680, alignSelf: "center", padding: spacing.lg, paddingBottom: 118 }, header: { minHeight: 164, alignItems: "flex-start", paddingTop: spacing.sm }, title: { ...typography.display, color: colors.textPrimary, marginTop: spacing.md }, subtitle: { ...typography.body, color: colors.textSecondary, marginTop: spacing.xs }, stack: { gap: spacing.md }, card: { padding: spacing.xl, borderRadius: radii.hero, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, icon: { width: 48, height: 48, alignItems: "center", justifyContent: "center", borderRadius: radii.md, backgroundColor: colors.tealMuted }, label: { ...typography.caption, color: colors.teal, letterSpacing: 1, marginTop: spacing.lg }, cardTitle: { ...typography.heading, color: colors.textPrimary, marginTop: spacing.xs }, time: { ...typography.caption, color: colors.textTertiary, marginTop: spacing.xxs }, body: { ...typography.body, color: colors.textSecondary, marginTop: spacing.md }, preview: { minHeight: 48, flexDirection: "row", alignItems: "center", gap: spacing.xs, marginTop: spacing.lg, paddingHorizontal: spacing.sm, borderRadius: radii.sm, backgroundColor: "#2B2417" }, previewText: { ...typography.caption, flex: 1, color: colors.warning }, note: { ...typography.caption, color: colors.textTertiary, textAlign: "center", marginTop: spacing.xl } });
