import { Ionicons } from "@expo/vector-icons";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { CompanyLogo } from "@/components/finance/CompanyLogo";
import type { MarketMover } from "@/data/markets";
import type { DataResource, MarketQuote } from "@/data/real";
import { formatPrice } from "@/data/stocks";
import { colors, spacing, typography } from "@/theme/tokens";

export function MarketMoverRow({ mover, quote, onPress }: { mover: MarketMover; quote?: DataResource<MarketQuote>; onPress: () => void }) { const resolved = quote?.status === "ready" || quote?.status === "stale" ? quote.data : null; const change = resolved?.changePercent ?? null; const up = (change ?? 0) >= 0; const price = resolved ? formatPrice(resolved.price) : quote?.status === "loading" || !quote ? "Loading…" : "Unavailable"; return <Pressable accessibilityLabel={`${mover.name}, ${mover.symbol}, ${price}${change === null ? "" : `, ${up ? "up" : "down"} ${Math.abs(change).toFixed(2)} percent`}`} accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><CompanyLogo color={mover.logoColor} name={mover.name} size={42} symbol={mover.symbol} /><View style={styles.identity}><Text style={styles.symbol}>{mover.symbol}</Text><Text numberOfLines={1} style={styles.name}>{mover.name}</Text></View><View style={styles.value}><Text style={styles.price}>{price}</Text><View style={styles.changeRow}>{change !== null ? <Ionicons color={up ? colors.positive : colors.negative} name={up ? "caret-up" : "caret-down"} size={11} /> : null}<Text style={[styles.change, { color: change === null ? colors.textTertiary : up ? colors.positive : colors.negative }]}>{change === null ? "No quote" : `${up ? "+" : "−"}${Math.abs(change).toFixed(2)}%`}</Text></View></View></Pressable>; }
const styles = StyleSheet.create({ row: { minHeight: 70, flexDirection: "row", alignItems: "center", gap: spacing.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, pressed: { opacity: .65 }, identity: { flex: 1 }, symbol: { ...typography.label, color: colors.textPrimary }, name: { ...typography.caption, color: colors.textTertiary, marginTop: 2 }, value: { alignItems: "flex-end" }, price: { ...typography.label, color: colors.textPrimary }, changeRow: { flexDirection: "row", alignItems: "center", marginTop: 3 }, change: { ...typography.caption } });
