import { Ionicons } from "@expo/vector-icons";
import * as Haptics from "expo-haptics";
import { useRouter } from "expo-router";
import { StyleSheet, Text, View } from "react-native";
import { PrimaryButton } from "@/components/foundation/Buttons";
import { OnboardingScaffold } from "@/components/onboarding/OnboardingScaffold";
import { useOnboarding } from "@/features/onboarding/OnboardingProvider";
import { saveMockSession, saveOnboarding } from "@/storage/preferences";
import { colors, radii, spacing, typography } from "@/theme/tokens";
export default function CompleteScreen() { const router = useRouter(); const { state, dispatch } = useOnboarding(); const finish = () => { const completed = { ...state, completed: true }; dispatch({ type: "complete" }); void Promise.all([saveOnboarding(completed), saveMockSession(true)]).then(() => { void Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); router.replace("/(tabs)"); }); }; return <OnboardingScaffold description="Your personalized market feed is ready." footer={<PrimaryButton label="Enter Today" onPress={finish} />} step={7} title="Your brief is set"><View style={styles.check}><Ionicons color={colors.background} name="checkmark" size={38} /></View><View style={styles.summary}><Summary label="Experience" value={state.experience ?? "Exploring"} /><Summary label="Interests" value={state.interests.slice(0, 3).join(" · ") || "Your selections"} /><Summary label="Watchlist" value={state.stocks.join(" · ") || "AAPL · MSFT · NVDA"} /><Summary label="Brief alerts" value={state.notificationsEnabled ? "Preference on" : "Preference off"} /></View><Text style={styles.disclaimer}>Preferences stay on this device. Data shown in demo mode is illustrative.</Text></OnboardingScaffold>; }
function Summary({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ check: { width: 76, height: 76, alignSelf: "center", alignItems: "center", justifyContent: "center", borderRadius: 30, backgroundColor: colors.teal }, summary: { overflow: "hidden", borderRadius: radii.lg, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, row: { minHeight: 62, padding: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, label: { ...typography.caption, color: colors.textTertiary, textTransform: "uppercase", letterSpacing: .8 }, value: { ...typography.label, color: colors.textPrimary, marginTop: 4 }, disclaimer: { ...typography.caption, color: colors.textTertiary, textAlign: "center" } });
