import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { StyleSheet, Text, View } from "react-native";
import { PrimaryButton, SecondaryButton } from "@/components/foundation/Buttons";
import { OnboardingScaffold } from "@/components/onboarding/OnboardingScaffold";
import { useOnboarding } from "@/features/onboarding/OnboardingProvider";
import { colors, radii, spacing, typography } from "@/theme/tokens";
export default function NotificationsScreen() { const router = useRouter(); const { state, dispatch } = useOnboarding(); const next = (enabled: boolean) => { dispatch({ type: "notifications", value: enabled }); router.push("/(onboarding)/complete"); }; return <OnboardingScaffold description="Choose a local preference now. We will not request system permission in this milestone." footer={<><PrimaryButton label={state.notificationsEnabled ? "Keep notifications on" : "Notify me later"} onPress={() => next(true)} /><SecondaryButton label="Not now" onPress={() => next(false)} /></>} skipLabel="Not now" onSkip={() => next(false)} step={6} title="Stay ahead without the noise"><View style={styles.hero}><View style={styles.icon}><Ionicons color={colors.teal} name="notifications" size={34} /></View><Text style={styles.heading}>Only the signals you choose</Text><Text style={styles.body}>Earnings, meaningful price moves, and briefings—never a flood of generic updates.</Text></View><View style={styles.note}><Ionicons color={colors.warning} name="shield-checkmark-outline" size={20} /><Text style={styles.noteText}>This stores a local preference only. No push service or device permission is connected.</Text></View></OnboardingScaffold>; }
const styles = StyleSheet.create({ hero: { alignItems: "center", gap: spacing.md, padding: spacing.xl, borderRadius: radii.hero, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, icon: { width: 72, height: 72, borderRadius: 26, alignItems: "center", justifyContent: "center", backgroundColor: colors.tealMuted }, heading: { ...typography.heading, color: colors.textPrimary, textAlign: "center" }, body: { ...typography.body, color: colors.textSecondary, textAlign: "center" }, note: { flexDirection: "row", gap: spacing.sm, padding: spacing.md, borderRadius: radii.md, backgroundColor: "#2A2418" }, noteText: { ...typography.caption, flex: 1, color: colors.warning } });
