import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { CompanyLogo } from "@/components/finance/CompanyLogo";
import { PrimaryButton } from "@/components/foundation/Buttons";
import { OnboardingScaffold } from "@/components/onboarding/OnboardingScaffold";
import { useOnboarding } from "@/features/onboarding/OnboardingProvider";
import { MOCK_STOCKS } from "@/features/onboarding/model";
import { colors, radii, spacing, typography } from "@/theme/tokens";
const logoColors = ["#3569D4", "#3573B8", "#4E9A62", "#B52F38", "#E49A25", "#4A73C9", "#3970C7", "#35799C", "#5A5FCC", "#D43535"];
export default function StocksScreen() { const router = useRouter(); const { state, dispatch } = useOnboarding(); const [query, setQuery] = useState(""); const filtered = useMemo(() => MOCK_STOCKS.filter((stock) => `${stock.symbol} ${stock.name}`.toLowerCase().includes(query.toLowerCase())), [query]); return <OnboardingScaffold description="Select at least 3 companies. You can add up to 15 from Search later." footer={<PrimaryButton disabled={state.stocks.length < 3} label={state.stocks.length < 3 ? `Select ${3 - state.stocks.length} more` : "Continue"} onPress={() => router.push("/(onboarding)/notifications")} />} step={5} title="Choose stocks to follow"><View style={styles.search}><Ionicons color={colors.textTertiary} name="search" size={20} /><TextInput accessibilityLabel="Filter suggested stocks" autoCapitalize="characters" onChangeText={setQuery} placeholder="Filter suggested stocks" placeholderTextColor={colors.textTertiary} style={styles.input} value={query} /></View><Text style={styles.count}>{state.stocks.length} OF 15 SELECTED</Text>{filtered.map((stock, index) => { const selected = state.stocks.includes(stock.symbol); return <Pressable accessibilityLabel={`${stock.name}, ${stock.symbol}`} accessibilityRole="checkbox" accessibilityState={{ checked: selected, disabled: !selected && state.stocks.length >= 15 }} disabled={!selected && state.stocks.length >= 15} key={stock.symbol} onPress={() => dispatch({ type: "toggleStock", value: stock.symbol })} style={[styles.row, selected && styles.selected]}><CompanyLogo color={logoColors[index % logoColors.length] ?? colors.tealMuted} name={stock.name} size={42} symbol={stock.symbol} /><View style={styles.copy}><Text style={styles.name}>{stock.name}</Text><Text style={styles.symbol}>{stock.symbol}</Text></View><Ionicons color={selected ? colors.teal : colors.textTertiary} name={selected ? "checkmark-circle" : "add-circle-outline"} size={24} /></Pressable>; })}</OnboardingScaffold>; }
const styles = StyleSheet.create({ search: { minHeight: 52, flexDirection: "row", alignItems: "center", gap: spacing.xs, borderRadius: radii.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, paddingHorizontal: spacing.md }, input: { flex: 1, color: colors.textPrimary, fontSize: 16 }, count: { ...typography.caption, color: colors.teal, letterSpacing: .8, marginTop: spacing.xs }, row: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: spacing.sm, borderRadius: radii.lg, padding: spacing.sm, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, selected: { borderColor: colors.teal, backgroundColor: colors.tealMuted }, copy: { flex: 1 }, name: { ...typography.label, color: colors.textPrimary }, symbol: { ...typography.caption, color: colors.textSecondary, marginTop: 2 } });
